export const MEMCACHE_LOGIN = 'MEMCACHE_LOGIN'
export const LOGIN_OUT = 'LOGIN_OUT'
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN'
export const SONGS_SET = 'SONGS_SET'
export const RECORD_SET = 'RECORD_SET'
export const SONGS_INFO = 'SONGS_INFO'
export const CLEAR_SONG = 'CLEAR_SONG'
